/// Flutter icons Printly_icon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Printly_icon
///      fonts:
///       - asset: fonts/Printly_icon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Printly_icon {
  Printly_icon._();

  static const _kFontFam = 'Printly_icon';
  static const String? _kFontPkg = null;

  static const IconData proudact = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
